### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by Matgen84** [vulgo/NoVPAJpeg#1]
Hi

Great job

The latest release appears as 1.2.8 in "Get Info" instead of v3. It is normal?

Edit: I compile with latest commits: same issue 1.2.8 instead of v4

Thanks

**Comment by vulgo** [comment]
Thanks. The plugin version will be pegged to whatever version of the Lilu SDK it was compiled with (by default a build script downloads the latest Lilu and sets the version accordingly).

The 'module version' will be updated manually with the GitHub release tag, e.g. for archives uploaded to GitHub 'releases' page.

Building from master you should get an archive named like
```
NoVPAJpeg.1.2.8-v4.RELEASE.zip
```

**Comment by Matgen84** [comment]
Hi. Sorry for my bad english.
Building from master with Lilu Debug 1.2.8, I get NoVPAJpeg.1.2.8-v4.RELEASE.zip. But 'Get Info' display only "version: 1.2.8".
It isn't pratical for users. In info.plist, there is 1.2.8 instead of $(MODULE_VERSION) like other Lilu's plugins: I don't understand why this change since v3.
If I use $(MODULE_VERSION) in  info.plist, the zip file is NoVPAJpeg.1.2.8-v4.RELEASE.zip. 'Get Info' display 'Version: 4'
Could you modify it from Source, please:
       <key>CFBundleShortVersionString</key>
	<string>$(MODULE_VERSION)</string>
	<key>CFBundleVersion</key>
	<string>$(MODULE_VERSION)</string>

Thanks
 
![capture d ecran 2018-11-18 a 07 53 02](https://user-images.githubusercontent.com/5956729/48669564-7250da80-eb07-11e8-9428-7c5f4b454caa.png)

**Comment by vulgo** [comment]
Ok we will use module version everywhere for the plugin, Lilu version can be changed in target build settings. Finder info shows both module version + Lilu version.
https://github.com/vulgo/NoVPAJpeg/commit/96381d1af2918deefb92d22cb453c7e916483c14

**Comment by Matgen84** [comment]
Great Job. Thanks a lot
